<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lb</string>
	</array>
	<key>name</key>
	<string>LB</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.lb</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.source.lb</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Module declaration</string>
			<key>match</key>
			<string>^\b(module)\b\s+(\S+)\s*;</string>
			<key>name</key>
			<string>meta.namespace-block.source.lb</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*\b(restricted)?\b\s*\b(class|global|interface|globals)\b(?:\s+(\S+)\s*(\[\[)(.*)(\]\])\s*(.*?)?)?$\n</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.lb</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.lb</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.source.lb</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.source.lb</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>source.c++</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.source.lb</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>variable.source.lb</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Class definition</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.source.lb</string>
				</dict>
			</dict>
			<key>name</key>
			<string>class.source.lb</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embed-c</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function-definition</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#embed-c</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.lb</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.lb</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\*/.*\n</string>
					<key>name</key>
					<string>invalid.illegal.stray-comment-end.lb</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.lb</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.number-sign.lb</string>
				</dict>
			</array>
		</dict>
		<key>embed-c</key>
		<dict>
			<key>begin</key>
			<string>\[\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.source.lb</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Embedded C++ code</string>
			<key>end</key>
			<string>\]\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.source.lb</string>
				</dict>
			</dict>
			<key>name</key>
			<string>c++</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
			</array>
		</dict>
		<key>function-definition</key>
		<dict>
			<key>begin</key>
			<string>^\s*(\b(?:readonly)?\s+(?:int|double|bool|integer|long|string|lstring|table|function|udata|callback|multi|any|\S+)\b)?(?:\s+)?([a-zA-Z0-9_]+)\s*(\()?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.lb</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.lb</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.lb</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.function.arguments.lb</string>
			<key>end</key>
			<string>\)?$</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.lb</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.lb</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.lb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.lb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.other.lb</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>An argument with a default value</string>
					<key>match</key>
					<string>\s*(\b(?:readonly)?\s+(?:int|double|bool|integer|long|string|lstring|table|function|udata|callback|multi|any|\S+)\b)?\s+([a-zA-Z0-9_]+)\s*(=)\s*([a-zA-Z0-9_]+)\s*(,)?</string>
					<key>name</key>
					<string>meta.function.argument.default.lb</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.lb</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.lb</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>An argument WITHOUT default value</string>
					<key>match</key>
					<string>\s*(\b(?:readonly)?\s+(?:int|double|bool|integer|long|string|lstring|table|function|udata|callback|multi|any|\S+)\b)?\s+([a-zA-Z0-9_]+)\s*(,)?</string>
					<key>name</key>
					<string>meta.function.argument.no-default.lb</string>
				</dict>
			</array>
		</dict>
		<key>lbtypes</key>
		<dict>
			<key>match</key>
			<string>\b(?:int|double|bool|integer|long|string|lstring|table|function|udata|callback|multi|any)\b</string>
			<key>name</key>
			<string>storage.type.lb</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lb</string>
	<key>uuid</key>
	<string>84447adf-0302-43a6-95b5-cbb37ee6c18b</string>
</dict>
</plist>
